### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Urban_Interaction_CV#1]
@popabczhang can you create a Licence file according to library you are using in this project?

Also as a rule of thumbs (I think that's what we agreed when we put you as an admin) it's bette to coordinate between us before to create a repo

**Comment by popabczhang** [comment]
I am not using any library yet in this repo. Since we didn't have any conclusion for which license to use. I will hold until we have the conclusion. 

I don't remember that we agreed on the rule of thumbs you mentioned. I remember that we agreed on that the naming style of repo needs to be coordinated. For all the repos in this Org, not a single one has been created before discussed with me. I can follow this rule if it applied to every repo but not only mines. Besides, I actually do not think this rule aligns with Media Lab's spirit: "don't ask for permissions". It is discouraging for creativity. Media Lab Github Org didn't actually limit the creation of repos.

**Comment by popabczhang** [comment]
Instead of asking for permission to create repos, I suggest that the admins of the org meet regularly to decide if any adjustment needs to be made for all the repos. 
All admins: @agrignard @LAAP @yasushisakai @RELNO 
Please let me know your thought.

**Comment by agrignard** [comment]
" I suggest that the admins of the org meet regularly to decide if any adjustment needs to be made for all the repos" => that'q the purpose of the Biweekly CityScope meeting
